FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    nginx \
    php-fpm \
    curl \
    wget \
    unzip \
    libnginx-mod-http-modsecurity \
    libmodsecurity3t64 \
    modsecurity-crs && \
    rm -rf /var/lib/apt/lists/*

COPY app/ /var/www/html/

COPY default.conf /etc/nginx/sites-available/default

COPY modsecurity/modsecurity.conf /etc/nginx/modsecurity.conf

COPY modsecurity/modsecurity_includes.conf /etc/nginx/modsecurity_includes.conf

COPY start.sh /start.sh

RUN chmod +x /start.sh

EXPOSE 80

CMD ["/start.sh"]
